//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtubeApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public int UserId { get; set; }
        public int VideoId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Comment Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
    }
}
